ladyclavijo/PF-Henry-FRONT

Bookbuster/src/main.jsx
=> Main file configuration

Bookbuster/src/redux/store.jsx
=> Store configuration

Bookbuster/src/redux/reducer/index.jsx
=> Reducer structure

Bookbuster/src/redux/reducer/index.jsx
Falto declarar initialState, lo declare como const
=> Reducer fixed

Bookbuster/src/redux/actions/actionsTypes.jsx, Bookbuster/src/redux/actions/index.jsx, Bookbuster/src/redux/reducer/index.jsx
=> Action getBooks

Bookbuster/src/components/Card/Card.jsx, Bookbuster/src/components/Cards/Cards.jsx, Bookbuster/src/components/Filters/Filters.jsx, Bookbuster/src/components/NavBar/NavBar.jsx, Bookbuster/src/components/Pagination/Pagination.jsx, Bookbuster/src/components/SearchBar/SearchBar.jsx, Bookbuster/src/pages/Details/Details.jsx, Bookbuster/src/pages/Form/Form.jsx, Bookbuster/src/pages/Landing/Landing.jsx
Hice el cuerpo básico de los componentes de react
=> Basic React components

Bookbuster/src/pages/Home/Home.jsx
=> Component home

Bookbuster/src/components/SearchBar/SearchBar.jsx, Bookbuster/src/redux/actions/actionsTypes.jsx, Bookbuster/src/redux/actions/index.jsx
Cambios en la estructura de SearchBar y creación de función getBookByName en redux/actions
=> Searchbar modified

src/components/NavBar/NavBar.jsx, src/pages/Landing/Landing.jsx
Cambie el titulo a ingles y movi el boton de login
=> Landing cambios

src/components/FormLanding/FormLanding.css, src/components/FormLanding/FormLanding.jsx, src/pages/Landing/Landing.jsx
Cree el form para registrarse o para ingresar si ya eres usuario, lo agregue en Landing
=> Form Log In & Sign Up

src/pages/Landing/Landing.css, src/pages/Landing/Landing.jsx
Cambiando la landing, faltaría la sección de Bestselling
=> Nuevo diseño de landing

src/components/Pagination/Pagination.jsx
=> Pagination fixed

.eslintrc.cjs, package-lock.json, package.json, postcss.config.js, src/App.css, src/components/Card/Card.jsx, src/components/Cards/Cards.jsx, src/index.css, src/main.jsx, src/pages/Home/Home.jsx, tailwind.config.js
Agregue tailwind (necesitan dar otra vez npm i)
Le di estilos a cards 
Las acomode para que se vean 3 cards por fila
Es responsive 👍
=> Tailwind, estilos a cards

src/pages/Details/Details.jsx
=> Price of delivery

src/pages/Landing/Landing.css, src/pages/Landing/Landing.jsx
La imagen ya quedo lo mas responsive que se pudo 🚀
=> adjusted image

src/App.jsx, src/pages/Buy/Buy.jsx, src/pages/Cart/Cart.jsx
=> new routes

src/components/NavBar/NavBar.jsx
Que no aparezca el icono para ir a Home, cuando estoy en Home
=> Remove icon on Home

src/components/NavBar/NavBar.css
La card que tenga el mouse encima ya se queda atras de las 2 navbar
=> Styled cards

src/pages/Landing/Landing.jsx
quite el form de login que puse por accidente
=> Bye form Landing

src/pages/Buy/Address.jsx, src/pages/Buy/Articles.jsx, src/pages/Buy/Buy.jsx, src/pages/Buy/Countries.jsx, src/pages/Buy/Payment.jsx, src/pages/Buy/Validaciones.jsx
=> Ya contratemos diseñador para los estilos plsss

src/App.jsx, src/pages/Sales/Sales.jsx, styles.css
Agregue la ruta, le puse navbar y agregue la fuente crimson-pro
=> Route sales

src/App.jsx, src/Styles/colors.css, src/components/NavBar/NavBar.css, src/components/NavBar/NavBar.jsx, src/components/ThemeProvider/ThemeProvider.jsx, src/index.css, src/pages/Buy/Buy.jsx
Implementado en el componente Buy para probar.
=> Prueba 1 DarkMode

src/Styles/colors.css, src/components/NavBar/NavBar.jsx, src/components/ThemeProvider/ThemeProvider.jsx, src/pages/Buy/Buy.jsx
=> updated switch button

src/pages/About/About.jsx, src/pages/Cart/Cart.jsx, src/pages/Details/Details.jsx, src/pages/Home/Home.jsx, src/pages/Landing/Landing.css, src/pages/Landing/Landing.jsx
=> add background
